#!/usr/bin/python3
from sys import argv
from math import sqrt

def rsa(value):
    i = 2
    sq = int(sqrt(value))

    while True:
        if value % i == 0:
            print("{}={}*{}".format(value, value // i, i))
            break
        if value % sq == 0:
            print("{}={}*{}".format(value, value // sq, sq))
            break
        i += 1
        sq -= 1

try:
    with open(argv[1]) as file:
        line = file.readline()
        value = int(line.split('\n')[0])
        rsa(value)
except:
    pass