#!/usr/bin/python3
from sys import argv
from math import sqrt

def factorize(value):
    i = 2
    sq = int(sqrt(value))

    if value < 2:
        return
    while True:
        if value % i == 0:
            print("{}={}*{}".format(value, value // i, i))
            break
        if value % sq == 0:
            print("{}={}*{}".format(value, value // sq, sq))
            break
        i += 1
        sq -= 1

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.split('\n')[0])
            factorize(value)
            line = file.readline()
except:
    pass